import { Company, User, Job, Review, Invoice } from "./types";

export const DEMO_COMPANY: Company = {
  id: "comp_apex",
  name: "Apex Home Services",
  phone: "(555) 234-5678",
  email: "hello@apexhomeservices.com",
  address: "1247 Oak Ridge Blvd, Austin, TX 78701",
};

export const DEMO_USERS: User[] = [
  {
    id: "user_owner",
    email: "owner@apex.com",
    name: "Marcus Rivera",
    role: "owner",
    companyId: "comp_apex",
    password: "demo123",
  },
  {
    id: "user_admin",
    email: "admin@apex.com",
    name: "Sarah Chen",
    role: "admin",
    companyId: "comp_apex",
    password: "demo123",
  },
  {
    id: "user_tech1",
    email: "mike@apex.com",
    name: "Mike Torres",
    role: "technician",
    companyId: "comp_apex",
    password: "demo123",
  },
  {
    id: "user_tech2",
    email: "lisa@apex.com",
    name: "Lisa Park",
    role: "technician",
    companyId: "comp_apex",
    password: "demo123",
  },
  {
    id: "user_cust1",
    email: "john.smith@email.com",
    name: "John Smith",
    role: "customer",
    companyId: "comp_apex",
    password: "demo123",
  },
  {
    id: "user_cust2",
    email: "emily.jones@email.com",
    name: "Emily Jones",
    role: "customer",
    companyId: "comp_apex",
    password: "demo123",
  },
];

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();

export const DEMO_JOBS: Job[] = [
  {
    id: "job_001",
    companyId: "comp_apex",
    customerId: "user_cust1",
    customerName: "John Smith",
    customerEmail: "john.smith@email.com",
    customerPhone: "(555) 111-2222",
    title: "AC Unit Repair & Tune-up",
    description: "Customer reports AC not cooling properly. Likely refrigerant or capacitor issue. Full system check requested.",
    status: "sold",
    assignedTo: "user_tech1",
    assignedName: "Mike Torres",
    estimateAmount: 320,
    invoiceAmount: 385,
    scheduledDate: daysAgo(2).slice(0, 10),
    scheduledTime: "10:00",
    completedAt: daysAgo(1),
    soldAt: daysAgo(2),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
    address: "482 Maple Street, Austin, TX 78702",
    notes: "Customer prefers morning appointments. Gate code 4821.",
    privateNotes: "Customer previously complained about pricing – be careful with upsells. Paid on time last year.",
    files: [
      {
        id: "f1",
        name: "before-ac.jpg",
        url: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400",
        isPrivate: false,
        uploadedAt: daysAgo(2),
        uploadedBy: "user_tech1",
      },
      {
        id: "f2",
        name: "invoice-internal.pdf",
        url: "#",
        isPrivate: true,
        uploadedAt: daysAgo(1),
        uploadedBy: "user_admin",
      },
    ],
    timeSpentMinutes: 95,
    soldBy: "user_tech1",
  },
  {
    id: "job_002",
    companyId: "comp_apex",
    customerId: "user_cust2",
    customerName: "Emily Jones",
    customerEmail: "emily.jones@email.com",
    customerPhone: "(555) 333-4444",
    title: "Water Heater Replacement",
    description: "50-gallon gas water heater replacement. Old unit is 14 years old and leaking.",
    status: "scheduled",
    assignedTo: "user_tech2",
    assignedName: "Lisa Park",
    estimateAmount: 1450,
    scheduledDate: new Date(now.getTime() + 86400000).toISOString().slice(0, 10),
    scheduledTime: "09:00",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
    address: "901 Cedar Lane, Austin, TX 78704",
    notes: "Permit already pulled by customer. Access through side gate.",
    privateNotes: "High-value lead from Google. Follow up for maintenance plan after install.",
    files: [],
    soldBy: "user_owner",
  },
  {
    id: "job_003",
    companyId: "comp_apex",
    customerId: "user_cust1",
    customerName: "John Smith",
    customerEmail: "john.smith@email.com",
    customerPhone: "(555) 111-2222",
    title: "Bathroom Faucet Install",
    description: "Replace kitchen and bathroom faucets. Customer supplied fixtures.",
    status: "estimate",
    estimateAmount: 180,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    address: "482 Maple Street, Austin, TX 78702",
    notes: "Fixtures already purchased – Moen.",
    privateNotes: "",
    files: [],
  },
  {
    id: "job_004",
    companyId: "comp_apex",
    customerId: "user_cust2",
    customerName: "Emily Jones",
    customerEmail: "emily.jones@email.com",
    customerPhone: "(555) 333-4444",
    title: "Electrical Panel Upgrade",
    description: "200A panel upgrade required for EV charger install.",
    status: "in_progress",
    assignedTo: "user_tech1",
    assignedName: "Mike Torres",
    estimateAmount: 2800,
    invoiceAmount: 2950,
    scheduledDate: daysAgo(0).slice(0, 10),
    scheduledTime: "08:00",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(0),
    address: "901 Cedar Lane, Austin, TX 78704",
    notes: "City inspection scheduled for Friday.",
    privateNotes: "Permit cost already billed. Materials from our preferred supplier.",
    files: [
      {
        id: "f3",
        name: "panel-photo.jpg",
        url: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400",
        isPrivate: false,
        uploadedAt: daysAgo(0),
        uploadedBy: "user_tech1",
      },
    ],
    timeSpentMinutes: 180,
    soldBy: "user_tech1",
  },
  {
    id: "job_005",
    companyId: "comp_apex",
    customerId: "user_cust1",
    customerName: "John Smith",
    customerEmail: "john.smith@email.com",
    customerPhone: "(555) 111-2222",
    title: "Dryer Vent Cleaning",
    description: "Full dryer vent and duct cleaning service.",
    status: "paid",
    assignedTo: "user_tech2",
    assignedName: "Lisa Park",
    estimateAmount: 149,
    invoiceAmount: 149,
    scheduledDate: daysAgo(10).slice(0, 10),
    completedAt: daysAgo(10),
    soldAt: daysAgo(12),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(9),
    address: "482 Maple Street, Austin, TX 78702",
    notes: "Annual service.",
    privateNotes: "Good recurring customer.",
    files: [],
    timeSpentMinutes: 45,
    soldBy: "user_tech2",
  },
];

export const DEMO_REVIEWS: Review[] = [
  {
    id: "rev_001",
    companyId: "comp_apex",
    jobId: "job_001",
    customerName: "John Smith",
    rating: 5,
    comment: "Mike fixed our AC the same day. Super professional and explained everything clearly. Highly recommend!",
    createdAt: daysAgo(1),
    status: "published",
  },
  {
    id: "rev_002",
    companyId: "comp_apex",
    jobId: "job_005",
    customerName: "John Smith",
    rating: 4,
    comment: "Quick and thorough dryer vent cleaning. Fair price.",
    createdAt: daysAgo(9),
    status: "published",
  },
  {
    id: "rev_003",
    companyId: "comp_apex",
    jobId: "job_002",
    customerName: "Emily Jones",
    rating: 0,
    comment: "",
    createdAt: daysAgo(1),
    requestedAt: daysAgo(1),
    status: "pending",
  },
];

export const DEMO_INVOICES: Invoice[] = [
  {
    id: "inv_001",
    jobId: "job_001",
    companyId: "comp_apex",
    customerId: "user_cust1",
    amount: 385,
    status: "paid",
    dueDate: daysAgo(0),
    paidAt: daysAgo(1),
    createdAt: daysAgo(1),
    lineItems: [
      { description: "AC diagnostic & refrigerant top-up", amount: 185 },
      { description: "Capacitor replacement", amount: 120 },
      { description: "System tune-up labor", amount: 80 },
    ],
  },
  {
    id: "inv_002",
    jobId: "job_004",
    companyId: "comp_apex",
    customerId: "user_cust2",
    amount: 2950,
    status: "sent",
    dueDate: new Date(now.getTime() + 7 * 86400000).toISOString().slice(0, 10),
    createdAt: daysAgo(0),
    lineItems: [
      { description: "200A panel upgrade materials", amount: 1450 },
      { description: "Labor (2 techs)", amount: 1200 },
      { description: "Permit & inspection coordination", amount: 300 },
    ],
  },
  {
    id: "inv_003",
    jobId: "job_005",
    companyId: "comp_apex",
    customerId: "user_cust1",
    amount: 149,
    status: "paid",
    dueDate: daysAgo(8),
    paidAt: daysAgo(9),
    createdAt: daysAgo(10),
    lineItems: [{ description: "Dryer vent cleaning service", amount: 149 }],
  },
];
